#
# default main.html block specification
#
pages:
  home:
    blocks:
      - blockUrl: header.html
        attr:
          style: 'position:fixed;z-index: 2;width:100%;top: 0px;background-color: #fff;'
      - blockUrl: frontBody.html
        attr:
          style: 'position:relative;z-index: 0;'
          styleSM: 'padding-right: 14px;'
          data-jnx-refresh-on: 'articles'             # refresh block on 'articlesUpdateItems' WS message from server
      - blockUrl: footer.html
        attr:
          style: 'position:relative;z-index: 0;margin-bottom: 0px;width:100%;background-color: #fff;'
  sideList:
    blocks:
      - blockUrl: header.html
        attr:
          style: 'position:fixed;z-index: 2;width:100%;background-color: #fff;'
      - blockUrl:
        attr:
          style: 'position:relative;'
        columns:
          - attr:
              ':xs': '24'
              ':sm': '8'
            blocks:
              - blockUrl: sideListBody.html
                attr:
                  style: 'padding: 6px;background-color: #fff;'
                  data-jnx-refresh-on: 'articles'
          - attr:
              ':xs': '24'
              ':sm': '16'
              styleXS: 'z-index: 1; position: relative;'
              styleSM: 'padding-right: 14px;'
            blocks:
              - blockUrl: article.html
                attr:
                  style: 'padding: 6px;background-color: #fff;'
                  data-jnx-refresh-on: 'articles'
      - blockUrl: footer.html
        attr:
          style: 'position:relative;z-index: 0;'
navigator:
  textColor: 'rgba(255, 255, 255, 1)'       # white text
  activeTextColor: 'rgba(255, 208, 75, 1)'  # active tab text (orange)
  backgroundColor: 'rgba(84, 92, 100, 1)'   # background of navigator (gray), drop downs have opacity=1
css:
  children:
    ".grayHeaders":                         # section block headers (gray)
      attributes:
        "background-color": "rgba(84, 92, 100, 0.73)"
    ".secColor":                            # color of slash in header (orange)
      attributes:
        "color": "#f68f44"
    ".secColorBg":                          # color of background of 'view all' (orange)
      attributes:
        "background-color": "#f68f44"
